### PR TITLE
Update faqs.md

### PR DESCRIPTION
**Pull request by blaazetech**
fixed typo

### CODE REVIEW

**Comment by jaydrogers** [comment]
Thanks dude! 👍

**Comment by blaazetech** [comment]
@jaydrogers no probs 😄 

on a side note, do you have any idea about how i can get out of this situation
[https://github.com/postalserver/postal/discussions/1580](https://github.com/postalserver/postal/discussions/1580)

**Comment by jaydrogers** [comment]
Haven't had a chance to dive into Postal with Docker yet. It's on my list.  😅

I will swing back once I get my feet wet with it more.

**Comment by blaazetech** [comment]
👍

**Pull request merged**
