### PR TITLE
Add link to new client library .net core

### PR DESCRIPTION
**Pull request by mDev86**
I am wrote new library (api client) for .NET Core. Add link in docs, please

### CODE REVIEW

**Review by willpower232 — APPROVED** [review]

**Comment by jbennink** [comment]
Please add this link, the .NET one (PostalServer-DotNet-Framework) currently listed is targeting full framework 4.5.2 and this on target .NET Core 7 and up. This would be a good addition.

**Comment by willpower232** [comment]
oh yeah, thanks for the nudge

**Comment by willpower232** [comment]
I've nudged my associates here so hopefully they have time to look at it soon.

**Comment by willpower232** [comment]
All sorted :tada:

**Pull request merged**
