### PR TITLE
Upgrade content-theme-docs to 0.9.0 and set defaultDir in settings

### LINKED ISSUE #2: Link to "Edit this page on GitHub" goes to the wrong URL
It seems to think all the docs are in a folder called `docs` whereas we have them in the root.

### PR DESCRIPTION
**Pull request by deanpcmad**
Fixes #2 

`content-theme-docs` v0.10.0 currently has a bug where it breaks formatting which is why I've gone with 0.9.0 - https://github.com/nuxt/content/issues/936

### CODE REVIEW

**Comment by adamcooke** [comment]
Thanks Dean. I actually fixed this a little earlier. I didn't spot your PR. I only upgraded to 0.6.0 though. We should probably go to 0.9.0. I've not used Nuxt Content before!

**Comment by willpower232** [comment]
it seems the latest version is 1.14, I also have no idea about Nuxt Content but is there any reason to use an older version?

**Comment by adamcooke** [comment]
I have no idea! It was 0.5.5 I think originally. I'm sure we could upgrade. I'll test it when I have a moment.

**Comment by jaydrogers** [comment]
I copied everything from my self-hosted email guide. I'll take a look at things tomorrow once I return 😀👍

**Pull request closed without merging**
