### PR TITLE
Nuxt 3 migration

### PR DESCRIPTION
**Pull request by casualmatt**
> [!WARNING]  
> **👷‍♂️🚧 This PR is still a work in progress.**

## 👨‍🔬 Preview URL
Use this URL to preview this PR:
- https://casualmatt.github.io/postal-docs/

## What this PR does
This PR performs a major upgrade for Nuxt Content from v2 → v3, as discussed in the original issue: https://github.com/postalserver/docs/issues/58

#### Static Site Technical Details
- [x] Migration from Nuxt 2 to Nuxt 3
- [x] Bulk migration of the pages from Nuxt content v2 to v3. 
- [x] Theme installation: Nuxt UI Pro Docs. 
- [x] Landing page with features
- [x] Add favicon

#### Docs README
- [x] Update the readme on how to contribute to the docs. 

- [ ] Ensure all PRs have automated preview URLs
- [ ] Production deployments should be automated with CI/CD from `main` as well

### CODE REVIEW

**Comment by jaydrogers** [comment]
Thanks for putting this together @casualmatt!

I updated your PR with some other todos that we'll need to check.

How do you feel on the GitHub Actions deployments? Looks like we'll need to get your Nuxt license loaded as a secret, but I might also have to factor some things for the automated PR previews.

Let me know what you need in order to help get this merged. Thanks a ton for your help!

**Comment by jaydrogers** [comment]
@casualmatt Awesome!

What else do we need before we send this off to review. See my list in your original comment. Let me know what you need help with!

**Comment by casualmatt** [comment]
For now just waiting for feedback for the homepage from @adamcooke, we already talk and as soon as his finished with the big part of V3 he will take a look.

Did u have the time to download it and test it? 
If yes any suggestions/feedback?

I'm waiting for V3 to migrate to the new components/blocs because the content of the docs will be rewritten in part.

**Comment by jaydrogers** [comment]
Will take a look soon! It's on my list and I hopefully will have more time available later this week 👍

**Comment by jaydrogers** [comment]
@adamcooke & @willpower232:

Could you take a look at the preview of @casualmatt's great work on this? You can see the site here: https://casualmatt.github.io/postal-docs/

Matt did a fantastic job putting this together. The search works very well and the them matches postal very well too.

### Next Steps
- What should be on the homepage? Right now he just left the boilerplate template in here. Let us know if you want to edit this yourself or work with @casualmatt on this directly.
- Review the docs and see if there is anything needed for the v3 upgrade

Any bugs or issues, just let us know in the comments below or you can open up individual issues and assign them to me. Thanks!

**Comment by willpower232** [comment]
Looks great to me, might need a different landing page initially haha

**Comment by casualmatt** [comment]
Yes, 
But IDK what to place there, so if you have a list of 6 features to add, please let me know.

**Comment by adamcooke** [comment]
Thanks for all your own on this @casualmatt.

What are the next steps for getting this PR now merged so we can get it live on docs.postalserver.io? To start with, it would be good to get this published and then I'll add some more content about v3 once we've got that sorted.

1. Do we need to update any config to handle publishing this to our domain instead of Matts?
2. The GitHub Actions references a secret called `secrets.NUXT_UI_PRO_LICENSE`, do we need to add that to the main `docs` repo?
3. Are there any other changes we need to make before making this live?

**Comment by casualmatt** [comment]
1. Yes we need to remove the CI from nuxt.studio and add the classic [GitHub pages for nuxt](https://nuxt.com/deploy/github-pages).  Will do it tomorrow. 
2. No. we need to add a setting on the nuxt.config.ts:
```ts
export default defineNuxtConfig({
  uiPro: { license: 'oss' }
})
```
3. tomorrow I will do a global check.

**Comment by adamcooke** [comment]
Is there a reason to remove Nuxt Studio or can we just use that if it works?

**Comment by casualmatt** [comment]
Ready to merge.

**Pull request merged**
