### PR TITLE
More notes

### PR DESCRIPTION
**Pull request by willpower232**
I found some notes whilst clearing out my laptop so thought I'd add them in.

### CODE REVIEW

**Comment by willpower232** [comment]
I had to re do the alert thing so thanks surge for pointing that out

**Comment by jaydrogers** [comment]
Nice! Glad you found Surge as a helpful tool! 👍

**Comment by willpower232** [comment]
One day I'll get round to reading the instructions and trying to run it myself 😅

**Review by lzadjsf — APPROVED** [review]
Good point.

**Pull request merged**
